apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
      annotations:
        instrumentation.opentelemetry.io/inject-go: "go-auto-instrumentation"
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/frontend"
    spec:
      containers:
      - name: frontend
        image: 10.0.0.1:5000/frontend:latest
