// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/backend/v1/backend.proto

package backendv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest) Reset() {
	*x = GetMessageRequest{}
	mi := &file_proto_backend_v1_backend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest) ProtoMessage() {}

func (x *GetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_v1_backend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest.ProtoReflect.Descriptor instead.
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_v1_backend_proto_rawDescGZIP(), []int{0}
}

func (x *GetMessageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageResponse) Reset() {
	*x = GetMessageResponse{}
	mi := &file_proto_backend_v1_backend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageResponse) ProtoMessage() {}

func (x *GetMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_v1_backend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageResponse.ProtoReflect.Descriptor instead.
func (*GetMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_backend_v1_backend_proto_rawDescGZIP(), []int{1}
}

func (x *GetMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetMessageResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_backend_v1_backend_proto protoreflect.FileDescriptor

const file_proto_backend_v1_backend_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/backend/v1/backend.proto\x12\n" +
	"backend.v1\"7\n" +
	"\x11GetMessageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\">\n" +
	"\x12GetMessageResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id2]\n" +
	"\x0eBackendService\x12K\n" +
	"\n" +
	"GetMessage\x12\x1d.backend.v1.GetMessageRequest\x1a\x1e.backend.v1.GetMessageResponseBCZAgithub.com/johnknl/otel-sandbox/pkg/protogen/backend/v1;backendv1b\x06proto3"

var (
	file_proto_backend_v1_backend_proto_rawDescOnce sync.Once
	file_proto_backend_v1_backend_proto_rawDescData []byte
)

func file_proto_backend_v1_backend_proto_rawDescGZIP() []byte {
	file_proto_backend_v1_backend_proto_rawDescOnce.Do(func() {
		file_proto_backend_v1_backend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_backend_v1_backend_proto_rawDesc), len(file_proto_backend_v1_backend_proto_rawDesc)))
	})
	return file_proto_backend_v1_backend_proto_rawDescData
}

var file_proto_backend_v1_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_backend_v1_backend_proto_goTypes = []any{
	(*GetMessageRequest)(nil),  // 0: backend.v1.GetMessageRequest
	(*GetMessageResponse)(nil), // 1: backend.v1.GetMessageResponse
}
var file_proto_backend_v1_backend_proto_depIdxs = []int32{
	0, // 0: backend.v1.BackendService.GetMessage:input_type -> backend.v1.GetMessageRequest
	1, // 1: backend.v1.BackendService.GetMessage:output_type -> backend.v1.GetMessageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_backend_v1_backend_proto_init() }
func file_proto_backend_v1_backend_proto_init() {
	if File_proto_backend_v1_backend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_backend_v1_backend_proto_rawDesc), len(file_proto_backend_v1_backend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_backend_v1_backend_proto_goTypes,
		DependencyIndexes: file_proto_backend_v1_backend_proto_depIdxs,
		MessageInfos:      file_proto_backend_v1_backend_proto_msgTypes,
	}.Build()
	File_proto_backend_v1_backend_proto = out.File
	file_proto_backend_v1_backend_proto_goTypes = nil
	file_proto_backend_v1_backend_proto_depIdxs = nil
}
